name: Henry Hub Signals

on:
  schedule:
    - cron: "0 8,16 * * *"
  workflow_dispatch:

jobs:
  run-signal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: DEBUG: Check EIA Key presence
        run: |
          if [ -n "\$EIA_API_KEY" ]; then
             echo "✅ EIA_API_KEY FOUND (value hidden by GitHub)"
          else
           echo "❌ ERROR: EIA_API_KEY is EMPTY"
          fi


      - name: Run signal script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          EIA_API_KEY: ${{ secrets.EIA_API_KEY }}
          STORAGE_CURRENT_BCF: ${{ secrets.STORAGE_CURRENT_BCF }}
          LAST_STORAGE_BUILD: ${{ secrets.LAST_STORAGE_BUILD }}
          STORAGE_FORECAST: ${{ secrets.STORAGE_FORECAST }}
        run: python henry_hub_signals.py

